---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic
  - src: git@github.com:cryptowebsite/kibana-role.git
    scm: git
    version: "v0.1.0"
    name: kibana
  - src: git@github.com:cryptowebsite/filebeat-role.git
    scm: git
    version: "v0.1.1"
    name: filebeat
  - src: git@github.com:cryptowebsite/logstash-role.git
    scm: git
    version: "v0.1.1"
    name: logstash
