---
- name: Elasticsearch
  hosts: elasticsearch
  gather_facts: yes
  roles:
    - ./roles/elastic
- name: Kibana
  hosts: kibana
  gather_facts: yes
  roles:
    - ./roles/kibana
- name: Filebeat
  hosts: filebeat
  gather_facts:
  roles:
    - ./roles/filebeat
- name: Logstash
  hosts: elasticsearch
  gather_facts: yes
  roles:
    - ./roles/logstash
