version: '3.9'

services:
  elasticsearch:
    container_name: elasticsearch
    image: centos:centos7
    restart: unless-stopped
    command: "tail -f /dev/null"
    networks:
      main:
        ipv4_address: "10.10.10.2"
  kibana:
    container_name: kibana-role
    image: centos:centos7
    restart: unless-stopped
    command: "tail -f /dev/null"
    networks:
      main:
        ipv4_address: "10.10.10.3"
  logstash:
    container_name: logstash
    image: centos:centos7
    command: "tail -f /dev/null"
    restart: unless-stopped
    networks:
      main:
        ipv4_address: "10.10.10.4"

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/29"
