- name: Configure new Elasticsearch
  become: true
  template:
    src: elasticsearch.yml.j2
    mode: 0644
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart Elasticsearch

  handlers:
  - name: restart Elasticsearch
    become: true
    service:
      name: elasticsearch
      state: restarted
    when: ansible_virtualization_type != 'docker